### ISSUE TITLE
Attributes usage

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-m-xsd#14]
For the `ebuttm:appliedProcessing` element, the [attributes `process` and `generatedBy`](https://github.com/ebu/ebu-tt-m-xsd/blob/master/ebu-tt-metadata.xsd#L544) are defined as required in the XSD though they are optional in Part M.

The same issue affects the `ebuttm:broadcastServiceIdentifier` element and its [attributes `serviceBegin` and `serviceEnd`](https://github.com/ebu/ebu-tt-m-xsd/blob/master/ebu-tt-metadata.xsd#L290).

**Comment by nigelmegitt** [comment]
Thanks for raising this. There is (internally in EBU) a spec issue about `serviceBegin` and `serviceEnd` on `ebuttm:broadcastServiceIdentifier` - the "mandatory" wording does not match the cardinality. It could be there is a similar spec problem here, I'm not sure without looking into it.

**Comment by nigelmegitt** [comment]
I checked the spec and `process` and `generatedBy` are unambiguously optional. I will open a pull request for this.
