### ISSUE TITLE
ttm:name/ttm:actor without namespace

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-m-xsd#6]
Currently the elements `ttm:name` and `ttm:actor` are [implicitely defined](https://github.com/ebu/ebu-tt-m-xsd/blob/master/metadata.xsd#L14) as child of the `ttm:agent` element. This however means that they have no namespace, instead of having the `ttm:` namespace, too, as required by TTML. So they should rather be defined on top level, like `ttm:agent` itself.

**Comment by nigelmegitt** [comment]
I think the same result can be achieved by setting `elementFormDefault="qualified"` on the `<xs:schema>` element in `metadata.xsd` - would that also work for you @spoeschel ?

**Comment by spoeschel** [comment]
Indeed - this is even better (I didn't know this way so far).
