### ISSUE TITLE
ebuttm:authorsGroupSelectedSequenceIdentifier min len

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-m-xsd#9]
The [attribute `ebuttm:authorsGroupSelectedSequenceIdentifier`](https://github.com/ebu/ebu-tt-m-xsd/blob/master/ebu-tt-metadata.xsd#L666) from Part M restricts the value to a minimum length of 1 char. However I cannot find that restriction in any spec.

**Comment by nigelmegitt** [comment]
This is a spec issue if it's not clear in tech3390. It is intended to match `ebuttp:sequenceIdentifier` which tech3370 specifies as `xs:string minLength="1"`.

**Comment by nigelmegitt** [comment]
I've raised an internal issue with EBU on the spec, and hope to be able to close this with no change.

**Comment by spoeschel** [comment]
Indeed this seems to be a spec issue. Thanks for raising the issue at EBU.
